scrape_configs:
  - job_name: 'QuranAppMetrics'
    metrics_path: 'localhost:8081/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Quran App'
